# Generated by Django 4.0.4 on 2022-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
